### ISSUE TITLE
create namespace packages

### ISSUE THREAD

**Issue by vincentsarago** [developmentseed/public-datasets#4]
in https://github.com/developmentseed/public-datasets/commit/473ac91a9d6afc3b01389b1acf8a6f0956d0b0a8 I've tried to split the code into subpacakges, this is still WIP but here is what I think we should have:

- public_datasets.api: `arturo-stac-api`API
- public_datasets.feeder: function and script to create the STAC items for the datasets
- public_datasets.stack: cdk code to deploy the stack

**Comment by kylebarron** [comment]
Is this fixed by #5? or keeping it open for visibility

**Comment by vincentsarago** [comment]
I think we can close, I'll open other about publishing/testing and lint
